### ISSUE TITLE
http://$API_HOST:5240/MAAS is rendered as http://:5240/MAAS

### ISSUE THREAD

**Issue by nobuto-m** [CanonicalLtd/maas-docs#1284]
The raw texts are written as `http://$API_HOST:5240/` but the rendered version in https://maas.io/docs/web-ui doesn't have `$API_HOST` which looks weird.

https://github.com/CanonicalLtd/maas-docs/blob/b8bebe4d013603f41a461521085f9a97c29e9ad3/en/installconfig-webui.md#access-the-web-ui

![Screenshot from 2019-09-30 16-28-21](https://user-images.githubusercontent.com/4356209/65857829-99bb3980-e39f-11e9-879a-4f5101ea719b.png)

**Comment by albertodonato** [comment]
Thanks, this is fixed now
