### ISSUE TITLE
Broken link to API docs

### ISSUE THREAD

**Issue by c-mart** [CanonicalLtd/maas-docs#131]
From here: http://maas.io/docs/en/manage-cli-common#reserve-ip-addresses
I click the link labeled "API documentation", which goes here: http://maas.ubuntu.com/docs/api

http://maas.ubuntu.com/docs/api gives me a 404. Confirmed on Firefox and Chromium, both running on Xubuntu 16.04.

**Comment by c-mart** [comment]
You probably want it pointing to http://maas.ubuntu.com/docs/api.html.

**Comment by pmatulis** [comment]
@c-mart Thank you

**Comment by pmatulis** [comment]
This problem should now be resolved automatically in the next publication of the docs.
