### ISSUE TITLE
Stale MAAS releases information

### ISSUE THREAD

**Issue by lathiat** [CanonicalLtd/maas-docs#132]
The general situation seems confusing, as we have multiple documentation URLs, e.g.
- http://maas.io/docs/
- http://maas.ubuntu.com/docs/
- http://maas.ubuntu.com/docs2.0/

Never the less, both the docs and docs2.0 versions on maas.ubuntu.com have stale information about releases.

http://maas.ubuntu.com/docs/ - no changelog entry for 2.0 (release)

http://maas.ubuntu.com/docs/changelog.html - no changelog entries for 2.0 (release)

http://maas.ubuntu.com/docs/releases.html - shows 2.0 still as the 'new development release' with estimated date of April 2016.  This page should probably flip the order so the newest release shows at the top.

**Comment by pmatulis** [comment]
This should be fixed now. Due to a fair amount of HTML redirects that were necessary to clear this up, it could be that some things were missed. Please document any that you may find in this issue and they will be fixed promptly. I'll close this for now.
