### ISSUE TITLE
maas.io api documentation link broken

### ISSUE THREAD

**Issue by rmcall** [CanonicalLtd/maas-docs#135]
the link to the API documentation is broken at maas.io.

The link to the page API Documentation page on http://maas.io/docs/en/ vor version 2.0 sends you to
http://maas.ubuntu.com/docs/api?_ga=1.165100663.991862073.1476504217

which results in 
The requested URL /docs/api was not found on this server.

**Comment by nottrobin** [comment]
Thanks @rmcall. This has been reported before (https://github.com/CanonicalLtd/maas-docs/issues/131) and we've fixed it but we haven't pushed the fix live yet. I'm working to confirm we're definitely okay to do a release, it should be fixed by end of tomorrow.

**Comment by pmatulis** [comment]
@nottrobin I don't see any reason to avoid publishing what's waiting in the repository.

I noticed the menu is missing changes that were published before. In PR #117 the (old) navigation.tpl took on links [Commission Nodes](http://maas.io/docs/en/installconfig-commission-nodes) and [Checklist](http://maas.io/docs/en/installconfig-checklist) but I don't see them anymore. A similar thing happened for changes made to the navigation in PR #118 .

**Comment by nottrobin** [comment]
@rmcall, @pmatulis I've just released the latest version to live, this should now be fixed. Closing.
