### ISSUE TITLE
No information about root login

### ISSUE THREAD

**Issue by faphdev** [CanonicalLtd/maas-docs#158]
Hello,
Nowhere in MAAS documentation does it say how to use a host after MAAS installed it.
I could not find how to set a password or an SSH key.

Thanks!

**Comment by pmatulis** [comment]
@faphdev Providing you're using 2.0 I suggest you read the [install & configure checklist](http://maas.io/docs/en/installconfig-checklist). See header 'Users and SSH keys'. Please report back - I'm interested in your feedback.

**Comment by pmatulis** [comment]
Due to the lack of feedback I will assume this is resolved. I'm closing this issue now but feel free to re-open if required.
