### ISSUE TITLE
Add warning that mark broken turns powers node off

### ISSUE THREAD

**Issue by szeestraten** [CanonicalLtd/maas-docs#183]
Please add a note or warning to the "Mark broken" section of [intro-concepts.md](https://github.com/CanonicalLtd/maas-docs/blob/9b3ab2c79cbf3a058909689ea5b4f4f0bd1de941/en/intro-concepts.md) that this action also powers off the node.

**Comment by pmatulis** [comment]
@szeestraten Thank you. This will be fixed momentarily (in the repository anyway).

**Comment by pmatulis** [comment]
Backported to 2.0 via #185
