### ISSUE TITLE
extraneous mention of Debian preseed on http://docs.ubuntu.com/maas/2.1/en/#what-maas-offers

### ISSUE THREAD

**Issue by brendan-donegan** [CanonicalLtd/maas-docs#196]
On http://docs.ubuntu.com/maas/2.1/en/#what-maas-offers the following paragraph appears:

"MAAS provides management of a large number of physical machines by creating a single resource pool out of them. Participating machines can then be provisioned automatically **(Debian preseed)** and used as normal. When those machines are no longer required they are "released" back into the pool. MAAS integrates all the tools you require in one smooth experience. It includes:"

The mention of Debian preseed looks out of place

**Comment by pmatulis** [comment]
I agree. Will fix.
