### ISSUE TITLE
Create custom image documentation / new feature?

### ISSUE THREAD

**Issue by tpmullan** [CanonicalLtd/maas-docs#203]
I can't find a way to create a custom image in the new docs for MaaS.  The website still says that it is possible, but there is nothing documented.  For example I need to install Oracle Linux and would like to try MaaS to simplify the process.

**Comment by pmatulis** [comment]
Hi @tpmullan . Can you provide the URL that refers to custom images?

**Comment by tpmullan** [comment]
So http://maas.io/ refers to Suse, Redhat and other operating systems, but http://docs.ubuntu.com/maas/2.1/en/installconfig-images-import has no information on how to create these images and use them.

**Comment by pmatulis** [comment]
Thank you. I'll investigate.

**Comment by pmatulis** [comment]
Currently, non-Ubuntu/CentOS and any type of custom image requires a commercial agreement with Canonical.

https://docs.ubuntu.com/maas/2.1/en/installconfig-images

I will close this issue.
