### ISSUE TITLE
It's unclear how to configure MaaS with HTTPS

### ISSUE THREAD

**Issue by c-mart** [CanonicalLtd/maas-docs#204]
As a sysadmin configuring MaaS, I see that the web interface uses HTTP insecurely, by default.  So, the first thing I want to do with a new MaaS server is secure my web UI with HTTPS. These instructions existed for version 1.9 ([link](https://maas.ubuntu.com/docs1.9/configure.html)) but seem to be missing from the current install guide [here](http://docs.ubuntu.com/maas/2.1/en/installconfig-package-install).

I found that the following procedure works, which could be indicated in the docs:

- `sudo a2enmod ssl` to enable Apache SSL module
- Add the following block to the top of `/etc/apache2/conf-enabled/maas-http.conf`, to redirect all connections to secure HTTPS:
  ```
  <VirtualHost *:80>
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
  </VirtualHost>
  ```
- Also in maas-http.conf, define `SSLCertificateFile` and `SSLCertificateKeyFile` to point to your certificate and private key respectively
- `service apache2 restart`

Regarding the project itself, I think that MaaS should adopt a secure default behavior of configuring its web interface with HTTPS and a self-signed certificate (much like the OpenStack Horizon dashboard does), and inviting the operator to provide their own certificate -- but now we are talking about "default configuration wishlist" rather than a documentation bug! :)

Also a general usability comment, it's unclear whether I should be using docs from http://docs.ubuntu.com/maas or from http://maas.ubuntu.com/docs/ -- they appear to be different. Perhaps the former is operator-oriented and the latter is developer-oriented, but this is not clearly indicated.

**Comment by pmatulis** [comment]
@c-mart Thank you for this. I'm wondering why you would choose to use ModRewrite to, effectively, change HTTP to HTTPS? Why not change the MAAS URL as proposed in the 1.9 page you referenced? Is it to make the change transparent to current users? You said this is a new installation.

**Comment by c-mart** [comment]
@pmatulis yes, it is a new installation, and my intention was to just redirect HTTP connections to HTTPS. I don't remember exactly why I set up a redirect to HTTPS instead of only changing the URL in the MAAS API -- sorry!

**Comment by pmatulis** [comment]
Because SSL can be implemented in various ways I didn't want to focus on just one solution such as Apache. I have so far left it up to the reader.

https://docs.ubuntu.com/maas/2.1/en/installconfig-network-ssl

**Comment by pmatulis** [comment]
I'm closing this if that's ok.
