### ISSUE TITLE
GUI instructions should take precedence over CLI

### ISSUE THREAD

**Issue by degville** [CanonicalLtd/maas-docs#21]
This may be required as part of a general documentation review, but examples attempt to reference the GUI rather than the CLI.

**Comment by pmatulis** [comment]
[ ] installconfig-add-nodes.md
[ ] installconfig-kernel.md
[ ] installconfig-he-kernels.md
[ ] installconfig-images-mirror.md
[ ] installconfig-network-static.md
[ ] installconfig-os-support.md
[ ] installconfig-sources.md

**Comment by pmatulis** [comment]
This is almost done. Storage is the only major piece that's left. Other stuff can be added (e.g. configure a node) time permitting.

**Comment by pmatulis** [comment]
I'm closing this. I'm tracking the storage and node configuring issues separately.
