### ISSUE TITLE
MAAS docs should be searchable

### ISSUE THREAD

**Issue by ryan-beisner** [CanonicalLtd/maas-docs#210]
MAAS docs should be searchable:

https://docs.ubuntu.com/maas/2.1/en/

**Comment by pmatulis** [comment]
@ryan-beisner Thank you for the reminder.

**Comment by pmatulis** [comment]
This has been raised in https://github.com/ubuntudesign/maas.io/issues/61 .

**Comment by nottrobin** [comment]
This will be solved in https://github.com/ubuntudesign/docs.ubuntu.com/issues/11. Closing this issue.
