### ISSUE TITLE
postgres ha backup

### ISSUE THREAD

**Issue by dustinkirkland** [CanonicalLtd/maas-docs#219]
On this page: https://docs.ubuntu.com/maas/2.1/en/manage-ha-postgresql

There are a couple of example commands for creating postgres backups: sudo mkdir -p /pgsql/archive
sudo chown postgres /pgsql/archive

I think these sample directories might be better as /var/backups/pgsql/archive

**Comment by pmatulis** [comment]
Thanks Dustin. That makes sense.
