### ISSUE TITLE
After configuring postgres hot standby, show how to verify it's working

### ISSUE THREAD

**Issue by dustinkirkland** [CanonicalLtd/maas-docs#220]
This page has excellent instructions on how to create a postgresql hot standby backup database:

https://docs.ubuntu.com/maas/2.1/en/manage-ha-postgresql

The one thing that could make it better, is adding a couple of commands at the very end, so that the user can verify that the backup is working properly.  Something like the following, on the Secondary section.

Verify that the Backup is working:
 # su - postgres
 $ psql
 postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 maasdb    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(4 rows)

**Comment by pmatulis** [comment]
Thanks for this good feedback.
