### ISSUE TITLE
Archived 1.9 docs full of broken image links

### ISSUE THREAD

**Issue by pmatulis** [CanonicalLtd/maas-docs#234]
Archived 1.9 docs full of broken image links. For example, see [here](https://docs.ubuntu.com/maas/1.9/en/install#installing-maas-from-ubuntu-server-boot-media).

**Comment by evilnick** [comment]
it works here...

**Comment by pmatulis** [comment]
It works for me now too.

**Comment by pmatulis** [comment]
This was fixed in https://github.com/ubuntudesign/docs.ubuntu.com/pull/38.
