### ISSUE TITLE
Common CLI task snippet to determine system ID returns multiple lines

### ISSUE THREAD

**Issue by szeestraten** [CanonicalLtd/maas-docs#248]
The common CLI task snippet for determining the system ID ([manage-cli-common.md#determine-a-system-id](../blob/master/en/manage-cli-common.md#determine-a-system-id)) returns multiple lines which is a bit annoying when using this as a variable.

This has worked previously, however it seems that `maas <profile> nodes read hostname=$HOSTNAME` now outputs multiple lines that contain `system_id` such as in the `blockdevice_set` and `interface_set` lists.

**Version:** MAAS 2.1.3

**Comment by pmatulis** [comment]
Thanks. I confirmed this.

**Comment by szeestraten** [comment]
A simple fix could be to add `-m 1` to the grep part to stop reading after the 1st match.

I can whip up a quick PR if you'd like.

**Comment by pmatulis** [comment]
@szeestraten You can surely do that. We encourage contributions. If not, I'll get it done this week. Publishing it may take longer.

**Comment by pmatulis** [comment]
I backported this to devel and 2.1.
