### ISSUE TITLE
Update MAAS 2.0 to MAAS 2.1

### ISSUE THREAD

**Issue by Juken-H** [CanonicalLtd/maas-docs#252]
I have updated the MAAS from 2.0 to 2.1. I use the command "apt upgrade" to finish upgrating the version.
but when the MAAS start, an error occurs, "maas@maasdb ERROR:  column maasserver_node.previous_status does not exist at character 243". Does MAAS 2.1 add new column to table "maasserver_node"?

**Comment by pmatulis** [comment]
@Juken-H I've never seen that message. Although it has been a few months since I upgraded to 2.1. Can you register a bug with the actual MAAS project?

https://bugs.launchpad.net/maas/+filebug

**Comment by Juken-H** [comment]
@pmatulis I registered the bug. If you want more information, please contact me, thanks!

**Comment by pmatulis** [comment]
@Juken-H Thank you. I saw it. Someone on the MAAS dev team should soon triage it. I'll close down this current bug. :fire_engine:
