### ISSUE TITLE
Add the word "secondary" when describing how to setup the API server in HA

### ISSUE THREAD

**Issue by dustinkirkland** [CanonicalLtd/maas-docs#260]
"On the host set aside for the new API server, add it by installing a few carefully chosen packages:"

This sentence would be better if it were a little less ambiguous, by adding the word "secondary"...

"On the secondary host set aside for the new API server, add it by installing a few carefully chosen packages:"

**Comment by pmatulis** [comment]
Thank you @dustinkirkland. I've put this on my todo list. :slot_machine:
