### ISSUE TITLE
Broken link to networking docs

### ISSUE THREAD

**Issue by Eeemil** [CanonicalLtd/maas-docs#262]
https://maas.ubuntu.com/docs/networking.html (popular result from google) leads to https://docs.ubuntu.com/maas/2.1/ennetworking.html which is broken.
I don't really know where the link should lead instead, but https://docs.ubuntu.com/maas/2.1/en/installconfig-networking could probably be it.

**Comment by pmatulis** [comment]
Thank you. I'll try to get a redirect set up.

**Comment by pmatulis** [comment]
This is fixed. Closing.
