### ISSUE TITLE
Migrate preseed/curtin from MAAS source code dev docs to user docs

### ISSUE THREAD

**Issue by pmatulis** [CanonicalLtd/maas-docs#283]
As per meeting with the MAAS team, the [preseed docs](http://bazaar.launchpad.net/~maas-committers/maas/trunk/view/head:/docs/development/preseeds.rst) should be upgraded from [Dev docs](http://bazaar.launchpad.net/~maas-committers/maas/trunk/files/head:/docs/development) to User docs.

Once done, these docs can be removed from the MAAS source code.

See also [LP #1668315](https://bugs.launchpad.net/maas/+bug/1668315).

**Comment by degville** [comment]
I'm going to migrate/update https://docs.ubuntu.com/maas/1.9/en/development/preseeds to master.
