### ISSUE TITLE
clarify the curtin preseed process

### ISSUE THREAD

**Issue by mimizone** [CanonicalLtd/maas-docs#288]
I would recommend to clarify the explanations of the curtin preseed process describe here
http://bazaar.launchpad.net/~maas-committers/maas/trunk/view/3608.4.40/docs/development/preseeds.rst

the naming of the preseed files part would gain from showing examples.
the name of the "release" is not clear for instance (thought it could have been 16.04, Xenial Xerus, or even the full name showing up on the MAAS UI "Ubuntu 16.04 LTS "Xenial Xerus""
what worked is the following:
`curtin_ubuntu_amd64_generic_xenial_nodename` 
nodename being the name of the node showing on the MAAS UI, without the domain. It is not the node-id that can be used on the MAAS API below.

the explanation of which files is being used and when during the maas enlist/commissioning/deployment process would help (difference between the curtin and curtin_userdata files for instance).
- I found that the `curtin_ubuntu_amd64_generic_xenial_osv16ocp3b` is properly retrieve during the first deployment boot, but the `late_commands` specified in it are not used.
- only the `curtin_userdata` or `curtin_userdata_ubuntu_amd64_generic_xenial_nodename` are used for the curtin commands in my experience. 

It's important to notice that any file specifically for a node (like `curtin_ubuntu_amd64_generic_xenial_nodename` or `curtin_userdata_ubuntu_amd64_generic_xenial_nodename` , would replace the generic files. Therefore anything from the generic templates needs to be copied to avoid the deployment process to stop and misbehave. The curtin file needs to contain the `{{preseed_data}}`, the curtin_userdata needs to contain in the late_commands section the wget command that disables the pxe boot in maas.

and also I found useful to use the internal API to retrieve the curtin file specifically for a node.
it would return for instance the content of the file `curtin_ubuntu_amd64_generic_xenial_nodename` after the substitution of the {{preseed_data}}
It helps to debug.
`curl -X GET http://$MAASIP/MAAS/metadata/latest/by-id/agqa6n/?op=get_preseed`
`agqa6n` being the node ID of the node, different from the node name.

I unfortunately couldn't figure out yet how to retrieve via the same API the curtin_userdata_ubuntu... file

**Comment by pmatulis** [comment]
Hi @mimizone. Thanks for this writeup. :beer:

**Comment by pmatulis** [comment]
Notes: curtin configuration is not preseed-like and does not digest preseed parameters but can take preseed info and forward it along, to dpkg for example. MAAS can however tell curtin to do certain things, like partitioning with MBR (as opposed to GPT).
