### ISSUE TITLE
Update/Create a new 16.04 Server ISO MAAS installation document

### ISSUE THREAD

**Issue by degville** [CanonicalLtd/maas-docs#32]

**Comment by evilnick** [comment]
you might want to check with Andres if they want people to install it that way. It certainly isn't as useful as it once was

**Comment by degville** [comment]
This is from Andres` feedback on the new TOC. He mentions that Mark is very keen on the ISO install. I've not tried it yet, but it also looks to have changed significantly, with the ISO boot menu now including options for both Rack and Region Controller options.

**Comment by evilnick** [comment]
Ok, in that case :+1:

**Comment by degville** [comment]
Fixed in #61
