### ISSUE TITLE
Errant backslashes in API docs

### ISSUE THREAD

**Issue by pmatulis** [CanonicalLtd/maas-docs#329]
Remove the backslashes from the parameters:

https://docs.ubuntu.com/maas/2.1/en/api

Example offense:

`param mac\_address MAC address of the interface.`

**Comment by pmatulis** [comment]
@nottrobin How should we handle this? Seems if we manually remove they will reappear the next time we take a snapshot with your script.

**Comment by nottrobin** [comment]
@pmatulis I'd say we should update the script. It might be fine to simply add something like `sed 's|\([a-z]\)\\_\([a-z]\)|\1_\2|'` to the end of the transformation command, and hope it doesn't catch anything it's not supposed to.

**Comment by degville** [comment]
This has been fixed with updates made to the API doc generating process. See #834.
