### ISSUE TITLE
[2.2] BMC power types need updating

### ISSUE THREAD

**Issue by pmatulis** [CanonicalLtd/maas-docs#397]
With MAAS 2.2 the [BMC driver feature table](https://docs.ubuntu.com/maas/devel/en/installconfig-power-types#bmc-driver-support) requires an update. There are two additions to make: 'Rack Scale Design' and  'Facebook's Wedge'.

This is waiting on the MAAS team to supply the raw information.

**Comment by newell** [comment]
Peter,

I would add another column called "Pod Management" or potentially change "Chassis Configuration" to "Chassis/Pod Configuration".

RSD and Virsh would be:

Rack Scale design = (PXE Next Boot, Power Querying, Pod Management)

Virsh will keep what it has but will also add (Pod Management)

I am less familiar with Facebook Wedge so you might want to get some other input on that but from looking at the code I believe this is what table entries it supports:

Facebook Wedge = (Power Query, BMC Enlistment)

**Comment by pmatulis** [comment]
I've also listed the Facebook Wedge as experimental. I think we're done here.
