### ISSUE TITLE
Hardware Requirements

### ISSUE THREAD

**Issue by jochenwezel** [CanonicalLtd/maas-docs#424]
the docs are missing an information on required/recommended hardware, e.g. required installed RAM for hosting a region controller

**Comment by pmatulis** [comment]
@jochenwezel 
This is on the very first page (index.html):
https://docs.ubuntu.com/maas/2.1/en/#minimum-requirements
Let me know if something is not clear.

**Comment by jochenwezel** [comment]
ah, okay, it was collapsed...after expanding that info, everything is clear...

Since this is important information, I'd recommend not to collapse this and keep it visible always.

**Comment by pmatulis** [comment]
@jochenwezel 
Thank you. This is good feedback.
