### ISSUE TITLE
Documentation for IP ranges needs updating for 2.2.

### ISSUE THREAD

**Issue by blakerouse** [CanonicalLtd/maas-docs#429]
IP range documentation needs to be updated for 2.2 and unmanaged subnets.

https://bugs.launchpad.net/maas/+bug/1690784

**Comment by pmatulis** [comment]
I don't see what is wrong with the current docs.

**Comment by blakerouse** [comment]
Ah I see my brain just skipped over the word managed. Maybe making the word managed bold give it more visibility.

Or maybe split up the points:

Reserved Ranges (managed subnet):

Reserved Ranges (unmanaged subnet):

**Comment by pmatulis** [comment]
Alright, I'll consider improving.

**Comment by pmatulis** [comment]
This is done. Closing.
