### ISSUE TITLE
[2.2] Docs needed - Adding a virsh Pod

### ISSUE THREAD

**Issue by pmatulis** [CanonicalLtd/maas-docs#430]
There is virsh Pod support since 2.2. We need docs highlighting this, including examples and screenshots.

**Comment by tmartinx** [comment]
Hi!

So, what I'm trying to do is something like this:

1- Install MaaS 2.2 from maas/next PPA on Ubuntu 16.04;
2- Deploy Ubuntu 16.04 in a bare metal server via PXE;
3- From MaaS node, ssh into the deployed server (ssh ubuntu@blade-1.maas);
4- Run: "sudo apt install ubuntu-virt-server" on the server;
5- Run: "virsh list", looks good;
6- Try to "Add pod" on MaaS, however, it is failing...

 Looks like that the field "Virsh address" doesn't accept anything! So far, I tried:

    qemu+ssh://ubuntu@blade-1.maas/system

Or:

    ubuntu@blade-1.maas

None worked! The following error appears on MaaS Web UI:

"Failed talking to pod: The command was not found or was not executable: virsh."

At the MaaS logs, I'm seeing:

rackd.log: http://paste.ubuntu.com/24582257/

regiond.log: http://paste.ubuntu.com/24582259/

 I'm giving up for now... I'll try to just PXE boot the VMs as bare metal servers and proceed with my installation.

Cheers!
Thiago

**Comment by pmatulis** [comment]
@tmartinx I've had success when using an IP address:

`qemu+ssh://ubuntu@192.168.1.2/system`

**Comment by pmatulis** [comment]
This has been done. Closing.

**Comment by tdihp** [comment]
@tmartinx have you installed `libvirt-bin` on your MAAS server? It seems from your log, `virsh` command is not found.
