### ISSUE TITLE
MAAS CLI - Image management

### ISSUE THREAD

**Issue by dhammo** [CanonicalLtd/maas-docs#431]
The image management section of the MAAS CLI does not clarify/define what is a boot-source and boot-resource. A customer was confused on what is boot-resource and boot-source. In addition, boot-resource has another api event called boot-resources.

To Create an image boot-resources is used
EX.  maas <admin> boot-resources create name=custom1 title=”Ubuntu Custom Image” architecture=amd64/generic content@=/home/ubuntu/ubuntu-custom-root-tgz

To Delete a boot-resource, the boot-resource delete command must be used, which is different that boot-source command
EX.  maas <admin> boot-resource delete 23 

A clarification of what boot-source, boot-resources, and boot-resource is needed to avoid confusion and wrong use of the api.

Thanks

**Comment by pmatulis** [comment]
@dhammo Thanks for this.
