### ISSUE TITLE
Make 1.9 docs a first-class citizen

### ISSUE THREAD

**Issue by pmatulis** [CanonicalLtd/maas-docs#454]
1.9 will be supported until April 2019 so it is well worth including it in the version selector area. The current state makes the MAAS docs look unfinished, hackish.

AFAIU, in order for our publishing mechanism to work, this implies a conversion (from the current static HTML pages) to Markdown. Since we did this already for 2.0 it shouldn't be too difficult to do it for 1.9.

@nottrobin

**Comment by degville** [comment]
fixed via #518, #519, #520, #522 and #543.

**Comment by evilnick** [comment]
:cake:
