### ISSUE TITLE
Dynamically convert and publish API docs

### ISSUE THREAD

**Issue by pmatulis** [CanonicalLtd/maas-docs#455]
We have devel docs published that refer to API calls (via the MAAS CLI) that are not covered by the corresponding API docs as they were only converted as a "one-off". We now need to dynamically convert them. I suppose this will need be a hook during the publication process. Maybe there can be a lever pulled during publication time that would turn this on, and for which release branch?

**Comment by pmatulis** [comment]
See #439 and #329

**Comment by degville** [comment]
I'm going to close this as the process has become a lot easier with the latest set of commands to generate the MAAS API docs (see #835), and should be part of each release update. We should revisit the automation issue when the docs live within the MAAS code repo.
