### ISSUE TITLE
Unclear how to log into the RESTful API using the API key from the user's account page

### ISSUE THREAD

**Issue by mkingsbury** [CanonicalLtd/maas-docs#549]
I'm trying to write a simple script in /pick your favorite language/ using the RESTful API.  A simple example of how to log into the API and perhaps perform a simple query about nodes that are in the ready state would go a long way to helping understand how to use the API.  I don't see any reference to logging into the API using the API key.  The syntactical documentation is great; the actual manner in how to use it is lacking.    Any references to the 'maas' CLI tool or an existing library should be avoided to remain platform and language agnostic.

Thanks!

**Comment by mkingsbury** [comment]
It appears the API authentication page from the 1.9 version of the docs was dropped.  Stumbled across this & was able to make some forward progress -

https://docs.ubuntu.com/maas/1.9/en/api_authentication

**Comment by degville** [comment]
fixed with #636
