### ISSUE TITLE
fabric definition update for MAAS

### ISSUE THREAD

**Issue by dshcherb** [CanonicalLtd/maas-docs#573]
A fabric is currently listed as:

https://github.com/CanonicalLtd/maas-docs/blame/2.2/en/intro-concepts.md#L120-L124
"A *fabric* is a set of interconnected VLANs that are capable of mutual communication. A fabric is a logical grouping of unique VLANs. A default fabric	('fabric-0') is created for each detected subnet when MAAS is installed."

However, in my view, this definition would be much better: "Fabric - a switch or a combination of switches that are trunked, all providing the same VLANs."

In other words: a MAAS region controller(s) (HA or not) manages a single region only. In a single region (e.g. data-center) you may have multiple floors (or other subdivisions) with different switch fabrics where VLAN "100" is not the same - that's why you need multiple fabrics in a single region. "Not the same" = no trunk connection exists between two switches providing the same number VLAN ID. Or, in an edge case, two switches may be connected but have no trunking configured (or different vlans configured on two sides) on ports used for mutual connectivity - that's two different fabrics.

This concept is similar to what [VXLAN](https://tools.ietf.org/html/rfc7348#section-6.1) does in a cloud environment - it virtualizes a physical network. A virtual network provides you an L2 with your own VLAN tags. MAAS fabric concept can be thought of a VLAN namespace mechanism (in the VXLAN world it would be a single VXLAN Network Identifier):

- 2^12 = 4096 unique IDs. VLAN ID 0 and 4095 are reserved by the standard, and VLANs 1-4094 are available for use according to the IEEE 802.1Q standard.
- 1 fabric = one 4096-ID space. A "fully-qualified" VLAN ID (reference) would be fabric:vlan_number.

Inter-VLAN communication is only possible via an L3 device so it could be mentioned that a [router-on-a-stick](https://en.wikipedia.org/wiki/One-armed_router) or an L3 switch must be present. This could be mentioned as well to make it more consumable by a casual user.

This is feedback from the field as people find "fabrics vs spaces" confusing given spaces became an L2 concept in 2.2.0:
https://github.com/CanonicalLtd/maas-docs/blame/2.2/en/intro-concepts.md#L127-L131

With network spaces there are several things in-place:

- 1:M VLANs per space
- 1:N subnets per VLAN
- 1:K fabrics per space (in other words: VLANs can be on different spaces)

But in the end it's a group of VLANs with a symbolic name where routing between the respective subnets works (e.g. via router-on-a-stick mechanism).

It would be nice to have a diagram as well showing all of those concepts mapped to a data center.

**Comment by degville** [comment]
Thanks for this fantastic write-up! We'll incorporate as much as we can into the docs.
Also, a diagram is an excellent idea - we'll create a separate issue for this, but if you get a moment to sketch something out, that would be hugely appreciated.

**Comment by dshcherb** [comment]
Can we incorporate this doc change into 2.2 branch?

https://docs.ubuntu.com/maas/2.2/en/intro-concepts#fabrics

**Comment by degville** [comment]
The definition was originally backported on GH, but due to a technical glitch, has yet to be published. This should automatically happen in the next day or two.
