### ISSUE TITLE
Preseed documentation not available for the latest versions of MAAS

### ISSUE THREAD

**Issue by iatrou** [CanonicalLtd/maas-docs#588]
How preseeds work is outlined at docs.ubuntu.com/maas/1.9/en/development/preseeds
The same content is not available for any subsequent versions of MAAS (e.g. under docs.ubuntu.com/maas/2.2/en/), despite the fact that it is still applicable.

**Comment by degville** [comment]
Thanks for the reminder. We'll try to get this updated for the 2.x docs this week. 

(see also #283)
