### ISSUE TITLE
Update how API docs are linked to from new navigation/TOC

### ISSUE THREAD

**Issue by degville** [CanonicalLtd/maas-docs#60]
We currently link to the developer and API sub-trees within the main TOC (http://maas.ubuntu.com/docs/). This will cause (recursion) problems when we replace the old TOC with our new one.

**Comment by pmatulis** [comment]
I talked to Andres on this topic today. We can discuss in San Diego and have a hangout with him but, essentially, if he gets md files in LP then we can use Jenkins to pull user and API docs together. I imagine "the devil is in the details".

**Comment by brendan-donegan** [comment]
These links are currently broken, here: http://maas.io/docs/en/, would resolving this issue fix that? Otherwise I can file a new one

**Comment by pmatulis** [comment]
The API stuff is effectively fixed. There are still some underlying details to work out but users can now access the API docs from the web site. I'm closing this. I will also create a new issue for the Dev docs.
