### ISSUE TITLE
maas backdoor image documentation is outdated - needs removal

### ISSUE THREAD

**Issue by dshcherb** [CanonicalLtd/maas-docs#612]
There used to be a way to inject credentials to ephemeral images for debugging purposes.

https://docs.ubuntu.com/maas/2.2/en/troubleshoot-faq#debugging-ephemeral-image

It still references root-image file while there is no longer such file available:

ls /var/lib/maas/boot-resources/current/ubuntu/amd64/ga-16.04/xenial/daily/
boot-initrd  boot-kernel  squashfs

This has been raised in this bug which got "won't fix" resolution:

https://bugs.launchpad.net/maas/+bug/1631116

We need to remove this documentation section for contemporary MAAS versions as it is no longer valid.

**Comment by degville** [comment]
Thanks for letting us know.

**Comment by dshcherb** [comment]
I've come up with a procedure to build a squashfs image with a backdoor https://gist.github.com/dshcherb/223ee2d08f0a382856d52e041e5c2ef8

I'd need to prettify it a little bit but I've tested that it works properly.

This is very useful and should be properly documented in my view as a last-resort debugging procedure.

**Comment by degville** [comment]
ok, thanks. I'll close this issue and create a new one to potentially test and document the new procedure.
