### ISSUE TITLE
MAAS backup - exporting postgres database.

### ISSUE THREAD

**Issue by preisner** [CanonicalLtd/maas-docs#615]
Hi,

There is something to be modified on the doc, MAAS Backup[1].
This doc explains how to export postgres database using a command, "postgres pg_dumpall".
It mentions that Postgres database service needs to stop in order to avoid conflicting updates during a backup.
However, if postgres database service is stopped, "postgres pg_dumpall" is not possible to export it. 
Therefore, the section, "Stop critical services" should be like this,

```
To avoid conflicting updates during a backup, stop the following services with the sudo systemctl stop <service> command:

* maas-dhcpd.service
* maas-rackd.service
* maas-regiond.service

Also, make sure there is no session established to the database before running the dump command.
psql -c  "SELECT * FROM pg_stat_activity"
```

In addition,
On a postgres documentation[2], 
'pg_dump' makes consistent backups while the dump is running.

> pg_dump is a utility for backing up a PostgreSQL database. It makes consistent backups even if the database is being used concurrently. pg_dump does not block other users accessing the database (readers or writers).

It sounds like it is not necessary the maas services also stop.
However, I'm not sure 'pg_dump' grantees transaction consistent backups.
'pg_dumpall' could be the same procedure to 'pg_dump' internally.

[1] https://docs.ubuntu.com/maas/2.2/en/manage-backup
[2] https://www.postgresql.org/docs/9.5/static/app-pgdump.html

**Comment by degville** [comment]
Thanks for letting us know!
