### ISSUE TITLE
MAAS API documentation lack a chapter about authentication.

### ISSUE THREAD

**Issue by ArKam** [CanonicalLtd/maas-docs#633]
As I'm trying to get a proper collection of requests using postman to be able to share it among my team, I'm unable to find reliable information regarding the way for a user to authenticate agains a MAAS API.

Here is the document that I'm reading: https://docs.ubuntu.com/maas/2.2/en/api
There is now chapter or example about how to log with the API. From what I read here and there MAAS is relying on OAuth1 but I can't manage to connect on our demo server.

What is the consumer key?
What is the consumer secret?
What is the access token?
What is the token secret?
What is the realm to use?

What kind of parameters should we send?
Should we add the authorization data to the headers or the body/request URL?

Thanks a lot team.

**Comment by mkingsbury** [comment]
I struggled with this, the 1.9 version of the docs has the info you need - 

https://docs.ubuntu.com/maas/1.9/en/api_authentication

There's python & ruby examples in there, I can probably whip up a perl example if it would be useful.

**Comment by ArKam** [comment]
I would rather take a look at a cURL exemple additionally to te already existing programmatical examples.

**Comment by degville** [comment]
Thanks for the comments here. The API authentication document from 1.9 has been ported to the 2.x docs, which I think solves this issue, but I'll create an enhancement issue to look into expanding the authentication documentation.

**Comment by ArKam** [comment]
Thanks a lot, indeed, it would be nice to get this enhancement as even if we know how to do it with python or whatever language you're using, it seems maas is not using the same naming convention in Oauth than other companies. Indeed, when using postman or some OAuth library, they're requiring the following elements:

* Consumer Key.
* Consumer Secret.
* Access Token.
* Token Secret.

However, within maas we only use the following one:

* Consumer Key.
* Key.
* Secret.

It is not clear what is what except for Consumer Key.
Should we consider that secret is for Consumer Secret?
Should we consider that key is for Token Secret?
Should we consider that Access Token is the whole API Key build from the three previous part?
