### ISSUE TITLE
Very confusing language

### ISSUE THREAD

**Issue by ernestmartinez** [CanonicalLtd/maas-docs#664]
MAAS Advanced CLI documentation:
Install Rack Controller

reference the note:
Note: The register command is only needed if the rack controller is not being added to a system that already houses an API server.

The sentence references a negative which made me have to read it several times to understand it.

Would read better if it just stated:

Do not use register command if API server exists.

**Comment by degville** [comment]
Thanks for bringing this to our attention, and you're absolutely right about the negative - we'll update the text.
