### ISSUE TITLE
MaaS + JUJU When deploying set random ip address (dns-name)

### ISSUE THREAD

**Issue by Keremasci** [CanonicalLtd/maas-docs#768]
Hi All,

We are trying to install Openstack using Juju (2.3.2) and MAAS (2.3).
When we try to load the application via Juju, we get a random rope.
for example when I want to work with 10.0.0.0/24 it uses the overlay (tenant) which is 192.168.1.0/24.

Q: How do I provide interface or ip assignments when distributing over the Juju? The same is true for LXD
Thanks

**Comment by degville** [comment]
Thanks for raising this issue.

However, as this is more of a support query than a specific issue with the MAAS documentation, you may want to direct your question to the MAAS IRC channel on Freenode (try http://webchat.freenode.net/?channels=maas), or one of the Juju contact channels (https://jujucharms.com/docs/stable/contact-us).

The upstream OpenStack MAAS documentation may also help (https://docs.openstack.org/charm-deployment-guide/latest/install-maas.html).
