### ISSUE TITLE
jq (1.5+dfsg-1) apparently does not work with single quotes - doc update

### ISSUE THREAD

**Issue by burnbrigther** [CanonicalLtd/maas-docs#800]
Maas docs show several commands with single quotes on page https://docs.maas.io/2.1/en/manage-cli-advanced#list-rack-controllers under section "Assign a network interface to a fabric" - single quotes shown for commands must be updated to double quotes for commands to work.

**Comment by degville** [comment]
Thanks for letting is know - we'll update the docs.
