### ISSUE TITLE
Search result URLs include embedded Google tag 

### ISSUE THREAD

**Issue by degville** [CanonicalLtd/maas-docs#871]
To reproduce:

- disable adblock/uBlock and go to:
https://docs.ubuntu.com/search?q=audit+events&domain=docs.maas.io
- Select top result.
- URL appears as:
https://docs.maas.io/devel/en/manage-audit-events?_ga=2.61920299.601468389.1524502876-1433997189.1524502876

![image](https://user-images.githubusercontent.com/7047542/39141729-852c6a56-4720-11e8-8d73-f4e81a16179b.png)

(@nottrobin, I'm not certain this is the best place to file this)

**Comment by nottrobin** [comment]
@degville why is this an issue? I think this happens as part of our standard Google Analytics setup. Is there a reason why links in search results should be an exception?

**Comment by nottrobin** [comment]
Google uses these query strings to track users between domains, as browser security models don't provide any other way to share context. You'll see these URLs appear all over the place. I manually remove them when I cope URLs all the time, and you can get extensions to strip them for you, but they are very common.

I agree they are obnoxious, but they are just a standard part of tracking with Google Analytics. Unless we revisit our use of GA (unlikely) these query strings will stay.

Closing this now.
