### ISSUE TITLE
Update Composable Hardware - Pod Images

### ISSUE THREAD

**Issue by newell** [CanonicalLtd/maas-docs#872]
All Pod images should be updated as there have been several new changes to Pods in general.  Pods now have tags and a zone associated with them.  Additionally, Virsh Pods have over commit ratio multipliers as well as a default storage pool option.

**Comment by degville** [comment]
Thanks for raising this. These issues have been flagged as #859 and #855 with the updates ready to be merged. Your PR does include extra info though - thanks!
