### ISSUE TITLE
Documentation for filing bugs points to Launchpad, not GitHub

### ISSUE THREAD

**Issue by sparkiegeek** [CanonicalLtd/maas-docs#91]
In [the docs about page](http://maas.ubuntu.com/docs/about.html#contributing) the reader is advised to file bugs at https://bugs.launchpad.net/maas/+filebug not https://github.com/CanonicalLtd/maas-docs/issues/new

**Comment by pmatulis** [comment]
Nice catch. The 1.9 docs haven't been updated yet. Thank you.

**Comment by pmatulis** [comment]
Right. So *at this time* only 2.0 is being tracked in GitHub. My email to the lists should have stated 2.0 explicitly.

**Comment by sparkiegeek** [comment]
Well, the same page is in the 2.0 docs on maas.ubuntu.com too!

http://maas.ubuntu.com/docs2.0/about.html#contributing

**Comment by pmatulis** [comment]
Grrr, yeah, this is a bit frustrating. Soon everything will be cleaned out. At this time we need the old docs site to supply the dev & api docs. I'll fix the "old" 2.0 contributing page.

**Comment by pmatulis** [comment]
https://code.launchpad.net/~petermatulis/maas/correct-how-to-contribute-to-docs/+merge/305221

**Comment by pmatulis** [comment]
I don't know why my merge proposal did not get applied. This is a small part of a bigger architectural change that is blocked (pending manager appraisal).

**Comment by pmatulis** [comment]
I declare this resolved. Some old links don't redirect but at least we're no longer misinforming. Please re-open if you find any other anomalies.
