### ISSUE TITLE
Note notation broken in 2.0 docs

### ISSUE THREAD

**Issue by charlesdunbar** [CanonicalLtd/maas-docs#919]
Similar to https://github.com/juju/docs/issues/2695 - when going to the 2.0 version of MAAS documentation, note callouts are blank.  Going to any other version of documentation fixes this.

Examples include:
https://docs.maas.io/2.0/en/
https://docs.maas.io/2.0/en/installconfig-checklist

**Comment by degville** [comment]
Thanks for letting us know. We'll get this fixed as soon as we can.

**Comment by degville** [comment]
closed with #940
