### ISSUE TITLE
maas docs imply 'vid 0' means 'untagged'

### ISSUE THREAD

**Issue by jhobbs** [CanonicalLtd/maas-docs#938]
In the 'allocte' operation docs, maas say: 'Match a subnet on a VLAN with the specified VID. Valid values range from 0 through 4094 (inclusive). An untagged VLAN can be specified by using the value "0".'

However, you can have untagged interfaces with any vlan ID, so this is misleading.

**Comment by degville** [comment]
Thanks for flagging this. We'll update the doc to avoid confusion but this API reference material is auto-generated from the maas-region binary upstream.
