### ISSUE TITLE
Recommission in commission scripts is available only from MaaS 2.4

### ISSUE THREAD

**Issue by masterofcloud1** [CanonicalLtd/maas-docs#986]
In the commission scripts documentation is written that a recommission metadata can be added to make the server recommission after some script. But according to https://bugs.launchpad.net/maas/+bug/1789727 it is not possible until version 2.4

**Comment by jsseidel** [comment]
There was a bad docs backport which has been reverted.

https://bugs.launchpad.net/maas/+bug/1789729
